### ISSUE TITLE
edit suggestion for problem 3 in lab exercise 1

### ISSUE THREAD

**Issue by ash-not-hydrated** [Methaphur/CS142-NISER#3]
https://github.com/Methaphur/CS142-NISER/blob/57bbb7e4281b52843ab21ae711f13b66a76b8ce8/Lab_Exercise_1.py#L84
the number '3' could be changed to 'k' and the code should do the do
thanks!

**Comment by Methaphur** [comment]
Thanks <3 .... I'm careless
